services:
  server:
    build:
      context: ./server
      dockerfile: ../docker/express/Dockerfile
    container_name: mern-ecommerce-backend
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server
      - /server/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
      - PORT=8000

  frontend:
    build:
      context: ./client
      dockerfile: ../docker/react/Dockerfile

    container_name: mern-ecommerce-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./client:/client
      - /client/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - server
      # - mongo
    networks:
      - mern-ecommerce
  # mongo:
  #   image: mongo:7
  #   container_name: mern-mongo
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - mongo_data:/data/db
  #   restart: unless-stopped

networks:
  mern-ecommerce:
    driver: bridge
