name: MERN-Ecommerce Pipline

on:
  push:
    branches: ["main"] # The Event: trigger on every push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setting ssh
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY"> ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      - name: build_react
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test/
            git pull origin main
            cd /home/esten/MERN-Ecommerce-Test/client
            npm ci 
            npm run build
            cp -r dist/* /home/esten/build/ 
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}

      - name: build docker image and push to dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test/
            docker build -f docker/express/Dockerfile --no-cache -t $IMAGE_NAME:$TAG_NAME .
            docker tag $IMAGE_NAME:$TAG_NAME $DOCKER_USER/$IMAGE_NAME:$TAG_NAME
            docker push $DOCKER_USER/$IMAGE_NAME:$TAG_NAME
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DOCKER_REGISTRY: docker.io
          IMAGE_NAME: mern-image
          TAG_NAME: latest
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}

      - name: deployment
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test           
            docker compose down
            docker compose pull 
            docker compose -f docker-compose.prod.yml up -d
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
