name: MERN-Ecommerce Pipline

on:
  push:
    branches: ["main"] # The Event: trigger on every push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: docker login to runner
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}

      - name: set tag for docker image
        run: echo "TAG_NAME=${GITHUB_SHA::7}" >> $GITHUB_ENV

      - name: build docker image and push to dockerhub
        run: |
          docker build -f docker/express/Dockerfile --no-cache -t $DOCKER_USER/$IMAGE_NAME:$TAG_NAME ./server
          docker tag $DOCKER_USER/$IMAGE_NAME:$TAG_NAME $DOCKER_USER/$IMAGE_NAME:latest
          docker push --all-tags $DOCKER_USER/$IMAGE_NAME
        env:
          DOCKER_REGISTRY: docker.io
          IMAGE_NAME: mern-image
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ssh to server and deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_REGISTRY,DOCKER_USER,DOCKER_PSW,IMAGE_NAME
          script: |
            cd /home/esten/MERN-Ecommerce-Test/
            git pull origin main
            cd /home/esten/MERN-Ecommerce-Test/client
            npm ci
            npm run build
            rm -rf /home/esten/build/*
            cp -r dist/* /home/esten/build/
            cd /home/esten/MERN-Ecommerce-Test
            echo "$DOCKER_PSW" | docker login $DOCKER_REGISTRY -u $DOCKER_USER --password-stdin
            docker pull $DOCKER_USER/$IMAGE_NAME:latest
            docker kill mern-server-container
            docker rm mern-server-container
            docker run -d \
            --name mern-server-container \
            -p 127.0.0.1:8000:8000 \
            --env-file ./server/.env \
            -e NODE_ENV=production \
            -e PORT=8000 \
            -v ./server:/server \
            -v /server/node_modules \
            $DOCKER_USER/$IMAGE_NAME:latest
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PSW: ${{ secrets.DOCKER_PASSWD}}
          IMAGE_NAME: mern-image
