name: MERN-Ecommerce Pipline

on:
  push:
    branches: ["main"] # The Event: trigger on every push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setting ssh
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY"> ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      - name: build_react
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test/
            git pull origin main
            cd /home/esten/MERN-Ecommerce-Test/client
            npm ci 
            npm run build
            cp -r dist/* /home/esten/build/ 
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}

      - name: build docker image and push to local registry
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test/
            docker build . -f docker/express/Dockerfile --no-cache -t $(DOCKER_REGISTRY)/$(IMAGE_NAME):$(TAG_NAME) && \
            docker login -u ${username} -p ${password} ${DOCKER_REGISTRY} && \
            docker push $(DOCKER_REGISTRY)/$(IMAGE_NAME):$(TAG_NAME)
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DOCKER_REGISTRY: docker.io
          IMAGE_NAME: mern-image
          TAG_NAME: v1
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}

      - name: deployment
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test
            docker login -u ${username} -p ${password} ${DOCKER_REGISTRY}            
            docker compose down
            docker compose pull 
            docker compose -f docker-compose.prod.yml up -d
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}
          DOCKER_REGISTRY: docker.io
          username: ${{ secrets.DOCKER_USERNAME}}
          password: ${{ secrets.DOCKER_PASSWD}}
