name: MERN-Ecommerce Pipline

on:
  push:
    branches: ["main"] # The Event: trigger on every push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: setting ssh
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY"> ~/.ssh/private_key
          chmod 600 ~/.ssh/private_key
          ssh-keyscan -H "$HOST" >> ~/.ssh/known_hosts

        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}

      - name: build_react
        run: |
          ssh -i ~/.ssh/private_key $USER@$HOST << 'EOF'
            cd /home/esten/MERN-Ecommerce-Test/
            git pull origin main
            cd /home/esten/MERN-Ecommerce-Test/client
            npm ci 
            npm run build
            cp -r dist/* /home/esten/build/ 
          EOF
        env:
          USER: ${{ secrets.USER }}
          HOST: ${{ secrets.HOST }}

      - name: Use SSH with TTY Emulation to build docker image and push to dockerhub
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_REGISTRYDOCKER_USER,DOCKER_PSW,IMAGE_NAME,TAG_NAME
          script: |
            cd /home/esten/MERN-Ecommerce-Test/
            docker build -f docker/express/Dockerfile --no-cache -t $DOCKER_USER/$IMAGE_NAME:$TAG_NAME .
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PSW 
            docker push $DOCKER_USER/$IMAGE_NAME:$TAG_NAME
        env:
          DOCKER_REGISTRY: docker.io
          IMAGE_NAME: mern-image
          TAG_NAME: latest
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PSW: ${{ secrets.DOCKER_PASSWD}}

      - name: deployment
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          envs: DOCKER_REGISTRY,DOCKER_USER,DOCKER_PSW
          script: |
            cd /home/esten/MERN-Ecommerce-Test
            docker login $DOCKER_REGISTRY -u $DOCKER_USER -p $DOCKER_PSW             
            docker compose down
            docker compose pull 
            docker compose -f docker-compose.prod.yml up -d
        env:
          DOCKER_REGISTRY: docker.io
          DOCKER_USER: ${{ secrets.DOCKER_USERNAME}}
          DOCKER_PSW: ${{ secrets.DOCKER_PASSWD}}
